projects:
- project_name: demo-app2
  description: "A sample project for demonstration"
  source:
    repo: 'https://github.com/ShivakumarDarapu/HOMELAB.git'
    path: 'jenkins_homelab'
    branch: 'main'
  destination:
    namespace: "jenkins"
    server: 'https://192.168.0.153:6443'
- project_name: gloo-gateway
  description: "gloo gateway"
  source:
    repo: 'https://github.com/ShivakumarDarapu/HOMELAB.git'
    path: 'gloo_gateway'
    branch: 'main'
  destination:
    namespace: "jenkins"
    server: 'https://192.168.0.153:6443'
