apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app1
  namespace: argocd
spec:
  project: demo-project
  source:
    repoURL: https://github.com/ShivakumarDarapu/HOMELAB.git
    targetRevision: main
    path: Deployments/jenkins_homelab
  destination:
    server: https://192.168.0.153:6443
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
