apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo-project1
  namespace: argocd
spec:
  description: A sample project for demonstration
  sourceRepos:
    - https://github.com/ShivakumarDarapu/HOMELAB.git
  destinations:
    - namespace: jenkins
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
