name: Workflow for Codecov example-java-maven
on: [push, pull_request]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: change dir
        run : cd ./DevSecOps/Test-App
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Install dependencies
        run: |
          cd ./DevSecOps/Test-App
          pwd 
          mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: Run tests and collect coverage
        run: |
          cd ./DevSecOps/Test-App
          pwd 
          mvn -B test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
  Build:
    runs-on: kubecli
    steps:
      - name: Build Docker Image 
        run: |
          cd ./DevSecOps/Test-App
          sh 'docker build -t dshivakumar/sample-java-app:""GIT_COMMIT""'
      - name: Docker Registery Authentication
        run: sh 'docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}'
      - name: DOCKER IMAGE PUSH 
        run: sh 'docker push dshivakumar/sample-java-app:""GIT_COMMIT""'