name: Workflow for Codecov example-java-maven
on: [push, pull_request]
jobs:
  TEST:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: change dir
        run : cd ./DevSecOps/Test-App
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Install dependencies
        run: |
          cd ./DevSecOps/Test-App
          pwd 
          mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - name: Run tests and collect coverage
        run: |
          cd ./DevSecOps/Test-App
          pwd 
          mvn -B test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build_Files
          path: ./DevSecOps/Test-App
          
  Build:
    runs-on: kubecli
    needs: [TEST]
    if: ${{ needs.TEST.result == 'success' }}
    steps:
      - name: Download Build Files
        uses: actions/download-artifact@v4
        with:
          name: Build_Files
      - name: Build Docker Image 
        run: |
          ls -al && ls -al ./target
          docker build -t "dshivakumar/sample-java-app:${{ github.run_id }}" .
      - name: Docker Registery Authentication
        run: sh 'docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}'
      - name: DOCKER IMAGE PUSH 
        run: sh 'docker push dshivakumar/sample-java-app:${{ github.run_id }}'