name: ARGO_CD_DEPLOY

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: kubecli
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: TEST HELM CHARTS
        run: | 
          cd k8s/myapps
          echo "Running helm lint..."
          lint_output=$(helm lint .)
          echo "$lint_output"
          
          if echo "$lint_output" | grep -q "Error"; then
            echo "❌ THERE WAS SOME ISSUE IN HELM CHART"
            echo "=== Helm Lint Output ==="
            echo "$lint_output"
            echo "=== Helm Template Output ==="
            helm template . --values ../../application_mapping.yaml
            exit 1
          else
            echo "✅ HELM CHARTS SEEM TO BE FINE"
          fi
        shell: bash
      # Runs a single command using the runners shell
      - name: Setting Kubernetes context
        run: kubectl config set-context default
      
      # Runs a set of commands using the runners shell
      - name: Deploying Apps
        run: |
          cd k8s/myapps
          helm upgrade myapps . --values ../../application_mapping.yaml --debug